# -*- coding: utf-8 -*-
"""MathematicsForDataScience_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0eSbbO4xbbAOU9zlGxayVEC4PK9D1cf
"""

import numpy as np
import matplotlib.pyplot as plt

A = np.array([
    [2, -1, 1, 0],
    [1, 1, 0, 1],
    [-1, 0, 3, -1],
    [0, 1, 1, 1]
], dtype=float)

B = np.array([150, 420, 100, 380], dtype=float)

X = np.linalg.solve(A, B)

print("Traffic flow solution:")
print("x1 =", X[0])
print("x2 =", X[1])
print("x3 =", X[2])
print("x4 =", X[3])

det_A = np.linalg.det(A)
print("Determinant of A =", det_A)

labels = ["x1", "x2", "x3", "x4"]

plt.bar(labels, X)
plt.title("Equilibrium Traffic Flows")
plt.xlabel("Road Link")
plt.ylabel("Vehicles per 10 minutes")
plt.show()

"""CALCULUS"""

import numpy as np

t = np.linspace(0, 10, 1000)

v = 70 + 12*np.cos(np.pi*t/5) - 4*np.sin(2*np.pi*t/5)

a = -(12*np.pi/5)*np.sin(np.pi*t/5) - (8*np.pi/5)*np.cos(2*np.pi*t/5)

max_acc = np.max(a)
min_acc = np.min(a)

t_max = t[np.argmax(a)]
t_min = t[np.argmin(a)]

print("Maximum acceleration:", max_acc)
print("Time at max acceleration:", t_max)

print("Minimum acceleration:", min_acc)
print("Time at min acceleration:", t_min)

plt.plot(t, v)
plt.title("Velocity vs Time")
plt.xlabel("Time (s)")
plt.ylabel("Velocity (km/h)")
plt.show()

plt.plot(t, a)
plt.title("Acceleration vs Time")
plt.xlabel("Time (s)")
plt.ylabel("Acceleration")
plt.axhline(0)
plt.show()

"""PROBABILITY"""

import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

mu = 0.85
sigma = 0.25

p_rapid = stats.norm.cdf(0.60, loc=mu, scale=sigma)

p_delayed = 1 - stats.norm.cdf(1.10, loc=mu, scale=sigma)

percentile_5 = stats.norm.ppf(0.05, loc=mu, scale=sigma)
percentile_95 = stats.norm.ppf(0.95, loc=mu, scale=sigma)

print("Probability of rapid reaction P(R < 0.60):", p_rapid)
print("Probability of delayed reaction P(R > 1.10):", p_delayed)
print("5th percentile:", percentile_5)
print("95th percentile:", percentile_95)

x = np.linspace(0, 2, 1000)
y = stats.norm.pdf(x, loc=mu, scale=sigma)

plt.plot(x, y)
plt.title("Normal Distribution of Autonomous Vehicle Reaction Times")
plt.xlabel("Reaction Time (seconds)")
plt.ylabel("Probability Density")

plt.axvline(0.60, linestyle="--", label="Rapid threshold: 0.60s")
plt.axvline(1.10, linestyle="--", label="Delayed threshold: 1.10s")
plt.axvline(percentile_5, linestyle=":", label="5th percentile")
plt.axvline(percentile_95, linestyle=":", label="95th percentile")

plt.legend()
plt.show()

"""STATISTICS"""

import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

speeds = np.array([49, 52, 55, 48, 50, 53, 57, 51, 54, 49, 52, 56])

n = len(speeds)
mean_speed = np.mean(speeds)
median_speed = np.median(speeds)
std_speed = np.std(speeds, ddof=1)
var_speed = np.var(speeds, ddof=1)

print("Sample size:", n)
print("Mean speed:", mean_speed)
print("Median speed:", median_speed)
print("Sample standard deviation:", std_speed)
print("Sample variance:", var_speed)

legal_limit = 50

t_stat, p_two_tailed = stats.ttest_1samp(speeds, popmean=legal_limit)

p_one_tailed = p_two_tailed / 2

print("t-statistic:", t_stat)
print("One-tailed p-value:", p_one_tailed)

plt.hist(speeds, bins=6)
plt.axvline(50, linestyle="--", label="Legal limit: 50 km/h")
plt.axvline(mean_speed, linestyle=":", label="Mean speed")
plt.title("Observed Vehicle Speeds in ISA Zone")
plt.xlabel("Speed (km/h)")
plt.ylabel("Frequency")
plt.legend()
plt.show()

